layout_spectrum: 0.1671751
typography_spectrum: 0.9761382
color:
  saturation: 0.941273
  lightness: 0.6474817
  brandStrength: 0.8963527
  rhythmicContrast: 0.7356492
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Jason Jobe
